#!/usr/bin/env bash

#
shellNS_main_boot_dependencies
unset shellNS_standalone_install_set_dependency
unset shellNS_main_boot_dependencies
unset shellNS_main_boot_dialog
unset SHELLNS_MAIN_DEPENDENCIES_REPO_LIST